version: 2.1

jobs:
  build_and_publish:
    docker:
      - image: cimg/base:stable
    parameters:
      ruby_version:
        type: string
      container_base:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --build-arg IMAGE=<< parameters.container_base >> \
              --build-arg RUBY_BERSION=<< parameters.ruby_version >> \
              -t ghcr.io/dashbrains/<< parameters.container_base >>/ruby:<< parameters.ruby_version >> .
      - run:
          name: Publish to Github Container Registry
          command: |
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker push ghcr.io/dashbrains/<< parameters.container_base >>/ruby:<< parameters.ruby_version >>       

workflows:
  build_and_publish:
    jobs:
      - build_and_publish:
          matrix:
            parameters:
              ruby_version: ['3.2.2', '3.1.4', '3.0.6']
              container_base: ['ubi9', 'ubi8']